name: Pull Request Pipeline
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: API Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: API Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: API Run Tests
        run: mvn -B test
  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: API Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: API Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: API Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: API Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: heyduedate-api
          path: heyduedate-api/target/heyduedate-api-1.0-SNAPSHOT.jar

      - name: REACT Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: REACT Install NPM packages
        run: npm ci
        working-directory: heyduedate-react
      - name: REACT Build project
        run: REACT_APP_API_URL=${{ secrets.API_URL }} npm run build
        working-directory: heyduedate-react
      - name: REACT Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: heyduedate-react
          path: ./heyduedate-react/build